---
- name: aws instance
  hosts: localhost
  connection: local
  tasks:
    - name: launch instance
      ec2:
        instance_type: t2.micro
        image: ami-0f2b4fc905b0bd1f1
        key_name: samdevops
        region: us-east-2
