#Every Day
'''
START INSTANCES AT 8AM MON-FRI
STOP INSTANCES AT 5PM MON-FRI
==========================
STEP1: CREATE A ROLE FOR LAMBDA FUNCTION
ALWAYS USE ROLE
STEP2: WRITE A LAMBDA FUNCTION USING BOTO3 OF PYTHON
'''